package(
    default_visibility = ["//:__subpackages__"],
)

licenses(["notice"])

filegroup(
    name = "images",
    srcs = glob(["*.png"]),
)

filegroup(
    name = "meshes",
    srcs = glob(["*.obj"]),
)
